import React from 'react'
import Head from 'next/head'

import { getNewReleaseChart } from '../api/api'
import NewReleaseChartPage from '../components/NewRelease/NewReleaseChartPage'

export default function NewSong({ data }) {
    return (
        <div >
            <Head>
                <title>Zing - Bài Hát</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <NewReleaseChartPage data={data} />
            </main>


        </div>
    )
}



export const getServerSideProps = async () => {

    const data = await getNewReleaseChart()

    if (!data) {
        return {
            props: {
                data: {},
            },
        }
    }

    return {
        props: {
            data,
        },
    }
}