import React from 'react'
import Head from 'next/head'
import { getTop100 } from '../api/api'


import Top100 from '../components/Top100/Top100'

const Top100Page = ({ data }) => {
    return (
        <div >
            <Head>
                <title>Zing - Top 100</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <Top100 data={data} />
            </main>


        </div>
    )
}

export default Top100Page

export const getServerSideProps = async () => {

    const data = await getTop100()

    if (!data) {
        return {
            props: {
                data: {},
            },
        }
    }

    return {
        props: {
            data,
        },
    }
}