import React from 'react'
import Head from 'next/head'

import { getChartHome } from '../api/api'
import ZingChartPage from '../components/Chart/ZingChartPage'

const ZingChart = ({ data }) => {
    return (
        <div >
            <Head>
                <title>Zing - Chart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <ZingChartPage data={data} />
            </main>


        </div>
    )
}

export default ZingChart

export const getServerSideProps = async () => {

    const data = await getChartHome()

    if (!data) {
        return {
            props: {
                data: {},
            },
        }
    }

    return {
        props: {
            data,
        },
    }
}