import React from 'react'
import { getlistMV } from '../../api/api'
import Head from 'next/head'

import Header from '../../components/Videos/Header'
import VideoList from '../../components/Videos/VideoList'

const MV = ({ data }) => {
    return (
        <div >
            <Head>
                <title>Zing - MV</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                <Header />
                <VideoList data={data} />
            </main>


        </div>
    )
}

export default MV


export async function getServerSideProps({ params }) {
    const id = params?.id
    const data = await getlistMV(`${id}`, 1, 20)

    if (!data) {
        return {
            props: {
                data: {},
            },
        }
    }

    return {
        props: {
            data,
        },
    }
}